### ISSUE TITLE
Multiple Copies with JavaScript Encoding & Turbolinks

### ISSUE THREAD

**Issue by mrj** [reed/actionview-encoded_mail_to#22]
When the ```encode: "javascript"``` option is used with Rails 5.2.2 on a Turbolinks-enabled page, an extra copy of the email address is rendered into the page every time the page is re-rendered by Turbolinks (link or back-button). You end up with a string like
```
contact@website.orgcontact@website.orgcontact@website.orgcontact@website.org
```

**Comment by MichalRemis** [comment]
I experience same behaviour with turbolinks. Solved it by removing inserted e-mail from page when leaving the page.

**Comment by reed** [comment]
Turbolinks is actually the main reason this was extracted from Rails.
