### ISSUE TITLE
Mail not encoded with encode hex

### ISSUE THREAD

**Issue by sylvain-farnault** [reed/actionview-encoded_mail_to#23]
Hi there,
I'm just trying this great feature, as it seams really useful, and planning to use onto some projects.

I did the basics stuffs:
 `gem 'actionview-encoded_mail_to'` in my _Gemfile_
`bundle install` in my _terminal_
I did had those green lines, so gem is well installed
`Fetching actionview-encoded_mail_to 1.0.9`
`Installing actionview-encoded_mail_to 1.0.9`

I inserted this test line in one of my views:
`<%= mail_to "someone@example.any", "someone's email", encode: "hex" %>`
But it has generated this:
`<a encode="hex" href="mailto:someone@example.any" class>someone's email</a>`
Mail is not encoded!

I am on Rails 5.2.4.2

Thanks a lot for your help
Sylvain

**Comment by reed** [comment]
I just tried it out on a Rails 5.2.4.2 app, and it worked as expected.  

It's curious that the element that you're seeing has a `class` attribute on it, when you didn't specify one.  Maybe you have something else installed that's also modifying the `mail_to` method?

**Comment by sylvain-farnault** [comment]
Well, I tried on a cleaner Rails app (which is 5.2.4.1), and it works.
Sorry, I'm not able to tell what went wrong on the first attempt! It was a messy test app!
Anyway, thanks a lot for your work 👍🏻
