### ISSUE TITLE
Email appear by hover the link with the mouse

### ISSUE THREAD

**Issue by Bertrand-Bichat** [reed/actionview-encoded_mail_to#24]
I use "hex" encode and on my localhost server, when I hover the link with my mouse, email appears in clear mode with my browser inspector.

Is that enough secured against spam ?

**Comment by reed** [comment]
If you inspect the link using the browser's developer tools, you'll see that the email address is hex encoded.  Any email harvester would have to go through the extra effort of decoding it in order to get the actual address.  It's not bulletproof.  The usefulness/effectiveness of this method is debatable.  That's why it was removed from Rails.

**Comment by Bertrand-Bichat** [comment]
> If you inspect the link using the browser's developer tools, you'll see that the email address is hex encoded. Any email harvester would have to go through the extra effort of decoding it in order to get the actual address. It's not bulletproof. The usefulness/effectiveness of this method is debatable. That's why it was removed from Rails.

Thank you for your answer. I agree that email address is well hex encoded when I click on the link, when I see the source code of the page and when I see the link with the browser's developer tools. But my question is about when I just mouseover on the link without click on it. In this case, the email address appear in clear mode at the bottom left of the browser's screen.

**Comment by reed** [comment]
Well the browser is smart enough to decode the links.  If it didn't, users might get confused if they saw the encoded link when they hovered over it.  

This encoding feature isn't meant to have any effect on anybody actually visiting your site in a browser.  It's meant to deter scripts that grab your site's source code and parse it looking for email addresses.
